// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PhoneDirectory.DataAccess.Concrete.EF;

namespace PhoneDirectory.WebApi.Migrations
{
    [DbContext(typeof(PhoneDirectoryContext))]
    partial class PhoneDirectoryContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.10")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("PhoneDirectory.Entities.Entities.ContactInfo", b =>
                {
                    b.Property<int>("ContactInfoID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("InfoContent")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("InfoType")
                        .HasColumnType("int");

                    b.Property<int>("UserID")
                        .HasColumnType("int");

                    b.HasKey("ContactInfoID");

                    b.HasIndex("UserID");

                    b.ToTable("ContactInfos");

                    b.HasData(
                        new
                        {
                            ContactInfoID = 1,
                            InfoContent = "1234567890",
                            InfoType = 0,
                            UserID = 1
                        },
                        new
                        {
                            ContactInfoID = 2,
                            InfoContent = "joey@email.com",
                            InfoType = 1,
                            UserID = 1
                        },
                        new
                        {
                            ContactInfoID = 3,
                            InfoContent = "1234567890",
                            InfoType = 0,
                            UserID = 2
                        },
                        new
                        {
                            ContactInfoID = 4,
                            InfoContent = "Rome",
                            InfoType = 2,
                            UserID = 2
                        });
                });

            modelBuilder.Entity("PhoneDirectory.Entities.Entities.User", b =>
                {
                    b.Property<int>("UserID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Company")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Surname")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserID");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            UserID = 1,
                            Company = "ABC",
                            Name = "Joey",
                            Surname = "Wayne"
                        },
                        new
                        {
                            UserID = 2,
                            Company = "DEF",
                            Name = "Uma",
                            Surname = "Rabbit"
                        });
                });

            modelBuilder.Entity("PhoneDirectory.Entities.Entities.ContactInfo", b =>
                {
                    b.HasOne("PhoneDirectory.Entities.Entities.User", "User")
                        .WithMany("ContactInfos")
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("PhoneDirectory.Entities.Entities.User", b =>
                {
                    b.Navigation("ContactInfos");
                });
#pragma warning restore 612, 618
        }
    }
}
